language: python
before_script:
 - make tests/env
 - echo "YES_PLEASE_DELETE_ALL_MY_DATA_VERY_OFTEN=Pretty please, with sugar on top." >> tests/env
 - echo "DATABASE_URL=postgres://postgres@localhost/gittip-test" >> tests/env
 - psql -U postgres -c 'CREATE DATABASE "gittip-test";'
 - make test-schema
script: make tests
notifications:
  email: false
  irc: 
    channels:
      - "irc.freenode.org#gittip"
    on_success: change
    on_failure: always
    template:
      - "%{repository} (%{branch}:%{commit} by %{author}): %{message} (%{build_url})"
    skip_join: true
